"""Local compiled-wiki layer for persistent AI Orchestrator knowledge.

The workflow follows three explicit layers:

1. ``raw/`` contains immutable source files.
2. ``wiki/`` contains compact Markdown pages maintained by agents.
3. ``WIKI_SCHEMA.md`` defines the operating contract.

No cloud service or embedding database is required. Raw sources are read during
ingest only; normal queries search the compiled wiki pages.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote


SCHEMA_VERSION = 1
SUPPORTED_SUFFIXES = {".csv", ".json", ".log", ".md", ".txt", ".yaml", ".yml"}
TOKEN_PATTERN = re.compile(r"\b[\w-]{3,}\b", re.UNICODE)
WIKILINK_PATTERN = re.compile(r"\[\[([^\]|#]+)")


class WikiError(RuntimeError):
    """Base error for wiki-layer operations."""


class ImmutableSourceError(WikiError):
    """Raised when an already-ingested raw source was modified."""


@dataclass(frozen=True)
class WikiPaths:
    root: Path

    @property
    def raw(self) -> Path:
        return self.root / "raw"

    @property
    def wiki(self) -> Path:
        return self.root / "wiki"

    @property
    def pages(self) -> Path:
        return self.wiki / "pages"

    @property
    def state(self) -> Path:
        return self.root / "state"

    @property
    def manifest(self) -> Path:
        return self.state / "manifest.json"

    @property
    def index(self) -> Path:
        return self.wiki / "index.md"

    @property
    def log(self) -> Path:
        return self.wiki / "log.md"

    @property
    def schema(self) -> Path:
        return self.root / "WIKI_SCHEMA.md"


DEFAULT_SCHEMA = """# AI Orchestrator Wiki Schema

## Ownership

- `raw/` is immutable source-of-truth material. Agents never edit ingested raw
  files. A corrected source is added as a new, versioned file.
- `wiki/pages/` is the compiled knowledge layer. Agents may create and update
  Markdown pages there.
- `state/manifest.json` records source hashes and ingest provenance.
- `wiki/index.md` is regenerated by tooling.
- `wiki/log.md` is append-only.

## Page conventions

- Keep one clear topic per page.
- Preserve source paths and SHA-256 citations.
- Use `[[wikilinks]]` for durable relationships.
- Mark mechanically generated pages as `status: draft`.
- An agent may promote a reviewed page to `status: curated`.
- Record contradictions instead of silently choosing one claim.

## Operations

1. Ingest: read a raw source once, create a compact draft page, update the
   manifest/index, and append the log.
2. Query: search the wiki first and read only returned pages. Read raw files only
   when verifying a citation or resolving a documented gap.
3. Lint: check immutable hashes, source/page coverage, index coverage, and
   unresolved wikilinks.
4. Curate: agents enrich draft pages, add synthesis/entity/concept pages, and
   preserve citations.
"""


def utc_now() -> str:
    return datetime.now(UTC).isoformat()


def initialize(paths: WikiPaths) -> None:
    paths.raw.mkdir(parents=True, exist_ok=True)
    paths.pages.mkdir(parents=True, exist_ok=True)
    paths.state.mkdir(parents=True, exist_ok=True)

    if not paths.schema.exists():
        paths.schema.write_text(DEFAULT_SCHEMA, encoding="utf-8")
    if not paths.manifest.exists():
        _write_json(
            paths.manifest,
            {"schema_version": SCHEMA_VERSION, "sources": {}, "updated_at": None},
        )
    if not paths.index.exists():
        paths.index.write_text("# Knowledge Index\n\n_No compiled pages yet._\n", encoding="utf-8")
    if not paths.log.exists():
        paths.log.write_text("# Knowledge Log\n", encoding="utf-8")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def load_manifest(paths: WikiPaths) -> dict[str, Any]:
    initialize(paths)
    try:
        manifest = json.loads(paths.manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise WikiError(f"invalid manifest: {exc}") from exc
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise WikiError("unsupported manifest schema version")
    if not isinstance(manifest.get("sources"), dict):
        raise WikiError("manifest sources must be an object")
    return manifest


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _relative_source(paths: WikiPaths, source: Path) -> tuple[Path, str]:
    resolved_raw = paths.raw.resolve()
    resolved_source = source.resolve()
    if not resolved_source.is_relative_to(resolved_raw):
        raise WikiError(f"source must be inside {paths.raw}: {source}")
    if not resolved_source.is_file():
        raise WikiError(f"source does not exist: {source}")
    relative = resolved_source.relative_to(resolved_raw)
    if relative.name.casefold() == "readme.md":
        raise WikiError("raw/README.md is documentation, not an ingest source")
    if relative.suffix.casefold() not in SUPPORTED_SUFFIXES:
        raise WikiError(f"unsupported source type: {relative.suffix or '<none>'}")
    return resolved_source, relative.as_posix()


def discover_sources(paths: WikiPaths) -> list[Path]:
    initialize(paths)
    return sorted(
        path
        for path in paths.raw.rglob("*")
        if path.is_file()
        and path.name.casefold() != "readme.md"
        and path.suffix.casefold() in SUPPORTED_SUFFIXES
    )


def _slug(source_path: str, digest: str) -> str:
    path_without_suffix = str(Path(source_path).with_suffix(""))
    normalized = re.sub(r"[^a-z0-9]+", "-", path_without_suffix.casefold()).strip("-")
    return f"{normalized or 'source'}-{digest[:8]}"


def _decode_source(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        raise WikiError(f"source must be UTF-8 text: {path}") from exc


def _title_for(source_path: str, text: str) -> str:
    for line in text.splitlines():
        heading = re.match(r"^#\s+(.+?)\s*$", line)
        if heading:
            return heading.group(1)
    return Path(source_path).stem.replace("-", " ").replace("_", " ").title()


def _compact_excerpt(text: str, limit: int = 2400) -> str:
    text = re.sub(r"\A---\s*\n.*?\n---\s*\n", "", text, flags=re.DOTALL)
    blocks = []
    for block in re.split(r"\n\s*\n", text):
        cleaned = block.strip()
        if not cleaned or cleaned.startswith("```"):
            continue
        blocks.append(cleaned)
        if sum(len(item) for item in blocks) >= limit:
            break
    excerpt = "\n\n".join(blocks)
    if len(excerpt) > limit:
        excerpt = excerpt[:limit].rsplit(" ", 1)[0] + "…"
    return excerpt or "_No textual content extracted._"


def _yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def compile_draft(source_path: str, digest: str, text: str, ingested_at: str) -> str:
    title = _title_for(source_path, text)
    source_link = "../../raw/" + quote(source_path)
    excerpt = _compact_excerpt(text)
    return f"""---
title: {_yaml_string(title)}
type: source
status: draft
source_path: {_yaml_string("raw/" + source_path)}
source_sha256: {_yaml_string(digest)}
ingested_at: {_yaml_string(ingested_at)}
---

# {title}

> Draft compiled mechanically from [{source_path}]({source_link}). An AI
> maintainer should refine the synthesis while preserving the source citation
> and SHA-256 hash.

## Key material

{excerpt}

## Provenance

- Source: `raw/{source_path}`
- SHA-256: `{digest}`
- Ingested: `{ingested_at}`
"""


def _frontmatter(page: Path) -> dict[str, str]:
    text = page.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    try:
        block = text.split("\n---\n", 1)[0].removeprefix("---\n")
    except IndexError:
        return {}
    metadata: dict[str, str] = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError:
            decoded = value
        metadata[key.strip()] = str(decoded)
    return metadata


def _page_summary(page: Path) -> str:
    text = page.read_text(encoding="utf-8")
    body = re.sub(r"\A---\s*\n.*?\n---\s*\n", "", text, flags=re.DOTALL)
    for block in re.split(r"\n\s*\n", body):
        cleaned = " ".join(line.strip() for line in block.splitlines())
        if not cleaned or cleaned.startswith("#") or cleaned.startswith(">"):
            continue
        return cleaned[:180]
    return "No summary available."


def rebuild_index(paths: WikiPaths) -> int:
    initialize(paths)
    entries = []
    for page in sorted(paths.pages.glob("*.md")):
        metadata = _frontmatter(page)
        title = metadata.get("title") or page.stem.replace("-", " ").title()
        status = metadata.get("status", "curated")
        entries.append(
            f"- [[pages/{page.stem}|{title}]] — {_page_summary(page)} "
            f"`status:{status}`"
        )
    content = "# Knowledge Index\n\n"
    content += "\n".join(entries) + "\n" if entries else "_No compiled pages yet._\n"
    paths.index.write_text(content, encoding="utf-8")
    return len(entries)


def _append_log(paths: WikiPaths, operation: str, detail: str, timestamp: str) -> None:
    with paths.log.open("a", encoding="utf-8") as log:
        log.write(f"\n## [{timestamp[:10]}] {operation} | {detail}\n")


def ingest(paths: WikiPaths, sources: Iterable[Path]) -> dict[str, list[str]]:
    manifest = load_manifest(paths)
    ingested: list[str] = []
    skipped: list[str] = []

    for source in sources:
        resolved, relative = _relative_source(paths, source)
        digest = _sha256(resolved)
        existing = manifest["sources"].get(relative)
        if existing:
            if existing.get("sha256") != digest:
                raise ImmutableSourceError(
                    f"raw source changed after ingest: {relative}; "
                    "restore it and add the revision as a new file"
                )
            skipped.append(relative)
            continue

        timestamp = utc_now()
        page_name = _slug(relative, digest) + ".md"
        page = paths.pages / page_name
        if page.exists():
            raise WikiError(f"compiled page collision: {page_name}")
        text = _decode_source(resolved)
        page.write_text(
            compile_draft(relative, digest, text, timestamp),
            encoding="utf-8",
        )
        manifest["sources"][relative] = {
            "sha256": digest,
            "size_bytes": resolved.stat().st_size,
            "wiki_page": f"wiki/pages/{page_name}",
            "status": "draft",
            "ingested_at": timestamp,
        }
        _append_log(paths, "ingest", relative, timestamp)
        ingested.append(relative)

    manifest["updated_at"] = utc_now()
    _write_json(paths.manifest, manifest)
    rebuild_index(paths)
    return {"ingested": ingested, "skipped": skipped}


def _tokens(text: str) -> list[str]:
    return [token.casefold() for token in TOKEN_PATTERN.findall(text)]


def query(paths: WikiPaths, search: str, top: int = 5) -> list[dict[str, Any]]:
    initialize(paths)
    terms = Counter(_tokens(search))
    if not terms:
        return []
    results = []
    for page in paths.pages.glob("*.md"):
        text = page.read_text(encoding="utf-8")
        metadata = _frontmatter(page)
        title = metadata.get("title", page.stem)
        title_tokens = Counter(_tokens(title))
        body_tokens = Counter(_tokens(text))
        score = sum(
            weight * (5 * title_tokens[term] + body_tokens[term])
            for term, weight in terms.items()
        )
        if score <= 0:
            continue
        excerpt = _matching_excerpt(text, terms)
        results.append(
            {
                "page": page.relative_to(paths.root).as_posix(),
                "title": title,
                "score": score,
                "excerpt": excerpt,
            }
        )
    return sorted(results, key=lambda item: (-item["score"], item["page"]))[:top]


def _matching_excerpt(text: str, terms: Counter[str], limit: int = 320) -> str:
    lowered = text.casefold()
    positions = [lowered.find(term) for term in terms if lowered.find(term) >= 0]
    start = max(0, min(positions, default=0) - 80)
    excerpt = " ".join(text[start : start + limit].split())
    return ("…" if start else "") + excerpt + ("…" if start + limit < len(text) else "")


def lint(paths: WikiPaths) -> dict[str, list[str]]:
    manifest = load_manifest(paths)
    errors: list[str] = []
    warnings: list[str] = []
    indexed = set(re.findall(r"\[\[pages/([^|\]]+)", paths.index.read_text(encoding="utf-8")))

    for relative, record in manifest["sources"].items():
        source = paths.raw / relative
        if not source.is_file():
            errors.append(f"missing raw source: {relative}")
        elif _sha256(source) != record.get("sha256"):
            errors.append(f"immutable raw source changed: {relative}")
        page_relative = record.get("wiki_page", "")
        page = paths.root / page_relative
        if not page.is_file():
            errors.append(f"missing compiled page for {relative}: {page_relative}")

    known_sources = set(manifest["sources"])
    for source in discover_sources(paths):
        relative = source.relative_to(paths.raw).as_posix()
        if relative not in known_sources:
            warnings.append(f"raw source not ingested: {relative}")

    pages = list(paths.pages.glob("*.md"))
    page_ids = {page.stem for page in pages}
    page_titles = {
        _frontmatter(page).get("title", page.stem).casefold(): page.stem for page in pages
    }
    for page in pages:
        if page.stem not in indexed:
            warnings.append(f"page missing from index: {page.name}")
        for target in WIKILINK_PATTERN.findall(page.read_text(encoding="utf-8")):
            normalized = target.removeprefix("pages/").strip()
            if normalized not in page_ids and normalized.casefold() not in page_titles:
                warnings.append(f"unresolved wikilink in {page.name}: {target}")

    return {"errors": sorted(set(errors)), "warnings": sorted(set(warnings))}


def stats(paths: WikiPaths) -> dict[str, Any]:
    raw_files = discover_sources(paths)
    wiki_files = list(paths.pages.glob("*.md"))
    raw_chars = sum(len(_decode_source(path)) for path in raw_files)
    wiki_chars = sum(len(path.read_text(encoding="utf-8")) for path in wiki_files)
    return {
        "raw_files": len(raw_files),
        "wiki_pages": len(wiki_files),
        "raw_characters": raw_chars,
        "wiki_characters": wiki_chars,
        "estimated_raw_tokens": math.ceil(raw_chars / 4),
        "estimated_wiki_tokens": math.ceil(wiki_chars / 4),
        "compiled_to_raw_ratio": round(wiki_chars / raw_chars, 4) if raw_chars else None,
        "note": "Character-based estimates measure corpus size, not guaranteed query savings.",
    }


def _print_query(results: list[dict[str, Any]]) -> None:
    if not results:
        print("No matching wiki pages.")
        return
    for result in results:
        print(f"## {result['title']} ({result['page']}, score={result['score']})")
        print(result["excerpt"])
        print()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("knowledge"))
    parser.add_argument("--json", action="store_true", dest="as_json")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("init")
    ingest_parser = subparsers.add_parser("ingest")
    ingest_parser.add_argument("sources", nargs="*", type=Path)
    query_parser = subparsers.add_parser("query")
    query_parser.add_argument("search")
    query_parser.add_argument("--top", type=int, default=5)
    subparsers.add_parser("lint")
    subparsers.add_parser("reindex")
    subparsers.add_parser("stats")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    paths = WikiPaths(args.root)
    try:
        if args.command == "init":
            initialize(paths)
            result: Any = {"initialized": str(paths.root)}
        elif args.command == "ingest":
            sources = args.sources or discover_sources(paths)
            result = ingest(paths, sources)
        elif args.command == "query":
            result = query(paths, args.search, args.top)
        elif args.command == "lint":
            result = lint(paths)
        elif args.command == "reindex":
            result = {"indexed_pages": rebuild_index(paths)}
        elif args.command == "stats":
            result = stats(paths)
        else:
            raise AssertionError(f"unhandled command: {args.command}")
    except WikiError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if args.as_json:
        print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    elif args.command == "query":
        _print_query(result)
    elif args.command == "lint":
        for error in result["errors"]:
            print(f"ERROR: {error}")
        for warning in result["warnings"]:
            print(f"WARNING: {warning}")
        if not result["errors"] and not result["warnings"]:
            print("Wiki lint passed.")
    else:
        print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))

    if args.command == "lint" and result["errors"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
